### ISSUE TITLE
Support installation using kustomize

### ISSUE THREAD

**Issue by erikgb** [google/kube-startup-cpu-boost#19]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do
not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

It seems like the only supported installation method currently is static manifests published as part of releases. While this works for a simple POC, I don't find it optimal for anything more.

This project appears to use the project layout suggested by kubebuilder, which I think is a good thing! 👍I would like to suggest some minor enhancements to better support installation using kustomize. Let me explain:

My team has created and is maintaining a few operators. Most of them are private source, but one is publicly available on GitHub: https://github.com/statnett/image-scanner-operator. This operator is installed in multiple on-prem clusters. To make the installation as simple as possible, we have extended the kubebuilder layout with an ["installation" kustomization on the project root](https://github.com/statnett/image-scanner-operator/blob/main/kustomization.yaml). The only responsibility beyond our kubebuilder default kustomization, is to set the correct image to use. Similar to this projects Makefile target producing the release manifests:

https://github.com/google/kube-startup-cpu-boost/blob/c421a4f84641631d5ae3241323e4a5af63dc9731/Makefile#L135-L138

With this project root kustomization, the installation from out on-prem kustomization could be as simple as:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/statnett/image-scanner-operator.git
```

This kustomization will produce the manifests for our default branch, using the latest release image, which is probably not "that" useful without a ref (tag). This is the core of our current on-prem installation:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  -  https://github.com/statnett/image-scanner-operator.git?ref=v0.6.32
```

**Note**: While others might prefer a Helm chart, we are trying to avoid Helm for various reasons.

WDYT @mikouaj?

### References

* #0000
