### ISSUE TITLE
too wide RBAC

### ISSUE THREAD

**Issue by camaeel** [google/kube-startup-cpu-boost#94]
IMHO operator doesn't need to update all secrets in the cluster, so secret access should be in the namespaced role. 

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-startup-cpu-boost-leader-election-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - update
    resourceNames:
      - kube-startup-cpu-boost-webhook-secret
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
```

ClusterRole can also be narrowed down only for it's own webhooks:
```
...
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - update
    resourceNames:
      - kube-startup-cpu-boost-validating-webhook-configuration
      - kube-startup-cpu-boost-mutating-webhook-configuration
...
```

Also I don't udnerstand what for is access to tokenreviews&subjectaccessreviews accesses and reading configmaps is needed. Seems to be obsolete.
